#!/usr/bin/env python3
"""Regression contracts for the GitHub-ready 3.8.9 release."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
errors: list[str] = []


def require(condition: bool, message: str) -> None:
    if not condition:
        errors.append(message)


config = json.loads((ROOT / "data/config.json").read_text(encoding="utf-8"))
routes = json.loads((ROOT / "data/routes.json").read_text(encoding="utf-8"))
package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
worker = (ROOT / "service-worker.js").read_text(encoding="utf-8")
readme = (ROOT / "README.md").read_text(encoding="utf-8")
version = "3.8.9"

require(config.get("versao") == routes.get("version") == package.get("version") == version, "versões divergentes")
require(f"qualimax-v{version}" in worker, "cache desatualizado")
require("Estudo de caso" in readme and "npm run test:e2e" in readme, "README de portfólio incompleto")

required = [
    ".nojekyll", ".editorconfig", ".gitignore", ".github/workflows/quality.yml",
    ".github/workflows/pages.yml", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "LICENSE.md",
    "playwright.config.js", "tests/e2e/site.spec.js", "tools/build-pages.py", "tools/run-tests.py",
    "docs/CASE-STUDY.md", "docs/NVDA-TEST-PLAN.md", "docs/assets/social-preview.png",
]
for relative in required:
    require((ROOT / relative).exists(), f"arquivo profissional ausente: {relative}")

pages = list(ROOT.glob("*.html")) + list((ROOT / "products").glob("*.html"))
products = list((ROOT / "products").glob("*.html"))
require(len(pages) == 81, f"esperadas 81 páginas, encontradas {len(pages)}")
require(len(products) == 60, f"esperadas 60 páginas de produto, encontradas {len(products)}")
marker = "Generated by tools/sync-client.py from data/products.json"
for path in products:
    require(marker in path.read_text(encoding="utf-8"), f"arquivo gerado sem marcador: {path.name}")

for workflow in ("quality.yml", "pages.yml"):
    text = (ROOT / ".github/workflows" / workflow).read_text(encoding="utf-8")
    require("actions/checkout@v7" in text, f"checkout atual ausente: {workflow}")
    require("permissions:" in text, f"permissões explícitas ausentes: {workflow}")

if errors:
    print("v3.8.9 FAILED\n" + "\n".join(errors))
    sys.exit(1)
print("v3.8.9 OK: GitHub, Pages, CI, documentação e 81 páginas validados")
